### ISSUE TITLE
Extract processus listen_queue from Osis-portal to Osis-common

### ISSUE THREAD

**Issue by basmot** [uclouvain/osis-common#10]
Lié à uclouvain/osis-portal#234
Lié à uclouvain/osis#1507

Tests:
- [x]  Ajout document-file dans osis et migration vers osis-portal
- [x]  Ajout document-file dans osis-portal et migration vers osis
- [x] Suppression document-file dans osis et migration (suppression) vers osis-portal
- [x] Suppression document-file dans osis-portal et migration (suppression) vers osis
- [x] Migration initiale (avec branche osis-portal#234 et osis#1507)  de person de osis-portal vers osis
- [x] Migration initiale (avec branche osis-portal#234 et osis#1507)  de person de osis vers osis-portal
- [x] Test fonctionnement de osis sans mise à jour (sans merge osis#1507)
- [ ] Test fonctionnement de osis-portal sans mise à jour (sans merge osis-portal#234)
